version: "3.5"
services:

  nginx:
      container_name: nginx-proxy
      image: ${ENV_NGINX_IMAGE}
      ports:
        - "80:80"
        - "443:443"
        - 500:5005
      environment:
        - "TZ:America/Detroit"
      volumes:
        - ~/cellxgene_VIP/data/:/data
        - ${ENV_SSL_CERT_DIR}:/certs/
        # - ${ENV_SHIB_CONF_DIR}:/etc/shibboleth/shibboleth2.xml
        # - ${ENV_HTML_FILE}:/usr/share/nginx/
        - ${ENV_CONTAINER_FILES}:/home/
