version: "3.5"
services:

  nginx:
      container_name: nginx-proxy
      image: ${ENV_NGINX_IMAGE}
      ports:
        - "80:80"
        - "443:443"
      environment:
        - "TZ:America/Detroit"
      volumes:
        - ~/cellxgene_VIP/data/:/data
        - ${ENV_SSL_CERT_DIR}:/certs/
        - ~/cellxgene_VIP/bin:/home/root
        - ${ENV_CONTAINER_FILES}/etc/nginx/sites-enabled/:/etc/nginx/sites-enabled/
        - ./bin:/home